### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by dixonge** [Desbeers/Chord-Provider#1]
Not in Mac App Store - no releases or packages on GitHub - how would I install this?

**Comment by Desbeers** [comment]
It is only source code; compile it with Xcode.

I have no intentions to release it in any other way.

**Comment by dixonge** [comment]
Ah, ok. Well it's doubtful i will ever have enough disk space for that so nvm...

**Comment by Desbeers** [comment]
Buy http://www.linkesoft.com/songbook/ from the AppStore.
I use it for years already and it it great. I made my own program just for fun...
