### ISSUE TITLE
PDF export separates chords and text

### ISSUE THREAD

**Issue by jbree** [Desbeers/Chord-Provider#12]
When exporting a PDF, one of the lines is cut off right in the middle of text.

Might be nice if the export tried to be smart about where it breaks so that chords always appear on the same page as lyrics. Or, even better, perhaps trying to keep whole sections on a page.

File attached showing where I observed the issue.

[Joshua Breeden - Fireflies.pdf](https://github.com/Desbeers/Chord-Provider/files/10320866/Joshua.Breeden.-.Fireflies.pdf)

**Comment by Desbeers** [comment]
Joshua, thanks for reporting this issue.

It should not be like that. You are correct, it should be smarter and whole sections should be on one page.

It's a though one to fix... However, I'm making progress!

I have all the sections of the song ready for the PDF export. I just have to put them in place; easier said than done, haha!

**Comment by Desbeers** [comment]
It should be fixed now with commit https://github.com/Desbeers/Chord-Provider/commit/2a9a235ba90801886de8ee91f190a0c9e76a76e0

**Comment by jbree** [comment]
Thanks, looks great!
