### ISSUE TITLE
{columns} directive

### ISSUE THREAD

**Issue by robertmiles3** [Desbeers/Chord-Provider#16]
Hello there! First, I just stumbled across this and am amazed at what you all have done. Great work! I'm a long-time dotnet developer and have recently picked up Swift as well. I'm just learning the guitar, so I came across this app.

I was wondering if there were any plans to add support for the `{columns}` directive? I noticed that the UI has the ability to view in list view or grid view (columns), but the PDF printout is always list view. It would be amazing to have columns support in the PDF as well. I would love to jump in an submit a PR, but I'm afraid my Swift skills are far behind my dotnet skills.

**Comment by robertmiles3** [comment]
Actually, reviewing the [ChordPro directives](https://www.chordpro.org/chordpro/chordpro-directives/#output-related-directives), it seems `{columns}` is a legacy directive. So, maybe the better thing to do would be to support `{column_break}` instead.

**Comment by Desbeers** [comment]
Hello Robert, thanks! Happy you like the program. I currently have no plans to add the `{column_break}` directive any time soon.

The UI view in grid is not really a *grid*, but more like the pages next to each other. Its rendered in SwiftUI so easy to do and I mostly use my music ‘on screen’ and so I can just see more content.

The PDF renderer is not really flexible and not easy to adjust.

If your main-goal is to produce good looking PDF’s, I recommend to use the official **ChordPro** implementation. Its PDF output is very customisable.

Currently, I’m rewriting the file parser to give a more flexible presentation and I will add the `{column_break}` to the todo list as a nice challenge :-)

**Comment by Desbeers** [comment]
I've added basic support to use the CLI of the official ChordPro implementation for PDF creation.

So if you have the **ChordPro** CLI installed you can use that instead of my limited PDF implementation.

https://www.chordpro.org/
