### ISSUE TITLE
German Chord names

### ISSUE THREAD

**Issue by SaschaMzH** [Desbeers/Chord-Provider#8]
In Germany the notes are CDEFGAH. It should be possible to translate this based on the system language to German automatically or to implement a settings screen.

**Comment by Desbeers** [comment]
CDEFGAH... I didn't know.

What do you expect? That the parser would translate the source 'B' to 'H' in the View or also respect 'H' in the ChordPro file itself?

**Comment by Desbeers** [comment]
See https://github.com/BeauNouvelle/SwiftyGuitarChords/issues/14 maybe?

**Comment by Desbeers** [comment]
No response...
