### ISSUE TITLE
end_of_xxx not used

### ISSUE THREAD

**Issue by SaschaMzH** [Desbeers/Chord-Provider#9]
It seams that there is a little bit magic because the end_of_xxx statements are not implemented.
This should be implemented to be more specific and ChordPro conform.

**Comment by Desbeers** [comment]
Good point and a lot of magic!

When I wrote Chord Provider it was just to make my cut/paste from internet reasonable.
A bit of *auto-detection*.
Later ; I added ChordPro directives; when I needed it.

It will look at every paragraph and makes a 'magic' dissision.

I will work on this; a bit of 'magic' will stay unless the magic is not not needed...

**Comment by Desbeers** [comment]
Fixed in https://github.com/Desbeers/Chord-Provider/commit/9e2f975b665063a8b1e860c6e3fb79bd52d48e85
